{% set name = "rplibs" %}
{% set version = "6.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rplibs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1b36074300932ac6653d93d4b0fe61e538d3353b786b2ec08dd7a66bf4b78b9f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - networkx >=2.5
    - brs_utils >=1.26.0
    - filetype
    - chemlite >=2.8.0
    - rr_cache
    - cobra
    - libsbml

test:
  imports:
    - rplibs

about:
  home: https://github.com/brsynth/rplibs/tree/main
  summary: "Defines an enriched SBML structure with additional fields relative to RetroPath2 objects."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - ramez17khaled
    - breakthewall
